#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Project2.Resource", IsApplication=true)]

namespace Project2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int AddRandomNoiseButton = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int ClearEffectsButton = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int GrayscaleButton = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int HighContrastButton = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int NegateBlueButton = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int NegateGreenButton = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int NegateRedButton = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int NewPhoto = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int RemoveBlueButton = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int RemoveGreenButton = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int RemoveRedButton = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int WoodgrainButton = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int launchCameraButton = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int takenPictureImageView = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Effect = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int file_paths = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
